### ISSUE TITLE
Reconstructions can't be found

### ISSUE THREAD

**Issue by gregmedlock** [mmundy42/mackinac#1]
Hello,

I can successfully create reconstructions with, for example:

modelseed.reconstruct_modelseed_model('1133568.3')

but any function meant to use this model (e.g. optimize_modelseed_model(), gapfill_modelseed_model()) raises a ServerError, such as:

ServerError: Can't call method "genome" without a package or object reference at /disks/p3dev2/deployment/lib/Bio/KBase/ObjectAPI/functions.pm line 521.

however, calling these functions on a model I made through the modelseed GUI works fine.

when I call modelseed.list_modelseed_models() using my folder ('/username/modelseed/'), the only models listed are those created in the GUI.

Any help is appreciated!

Thanks,
Greg

**Comment by mmundy42** [comment]
Can you post examples of the calls to the functions that don't work? And are you using a PATRIC or RAST authentication token?

**Comment by gregmedlock** [comment]
Using a PATRIC authentication token: 

modelseed.get_token('gregmedlock',password='...', token_type='patric', timeout=5)

The following works:

modelseed.reconstruct_modelseed_model('1133568.3')

Then neither of the following work:

modelseed.optimize_modelseed_model('1133568.3')
modelseed.gapfill_modelseed_model('1133568.3')

**Comment by mmundy42** [comment]
Can you run this command and post the output:

```modelseed.list_workspace_objects('/gregmedlock@patricbrc.org/modelseed', print_output=True)```

For the model you reconstructed there should be a line in the output that looks similar to this:

```don mmundy@patricbrc.org	         0	2017-01-03T22:10:42	modelfolder 	/mmundy@patricbrc.org/modelseed/1133568.3```

The important thing is that the type of the object is "modelfolder" instead of "folder".

My guess is that this is the first time you used a PATRIC authentication token with ModelSEED. It turns out that there are separate workspaces depending on if you use PATRIC or RAST tokens and a bug in the workspace if the "modelseed" folder does not exist before creating the first model.

**Comment by gregmedlock** [comment]
Here's the output:

Contents of /gregmedlock@patricbrc.org/modelseed:
don gregmedlock@patricbrc.org	         0	2017-01-03T20:21:00	modelfolder 	/gregmedlock@patricbrc.org/modelseed/Deino test
don gregmedlock@patricbrc.org	         0	2017-01-03T19:49:58	folder      	/gregmedlock@patricbrc.org/modelseed/1133568.3
-on gregmedlock@patricbrc.org	   1296836	2017-01-03T20:52:02	model       	/gregmedlock@patricbrc.org/modelseed/1133568.3/model
-on gregmedlock@patricbrc.org	   1219815	2017-01-03T20:52:02	string      	/gregmedlock@patricbrc.org/modelseed/1133568.3/1133568.3.sbml
-on gregmedlock@patricbrc.org	     68656	2017-01-03T20:52:02	string      	/gregmedlock@patricbrc.org/modelseed/1133568.3/1133568.3.cpdtbl
don gregmedlock@patricbrc.org	         0	2017-01-03T19:49:59	folder      	/gregmedlock@patricbrc.org/modelseed/1133568.3/gapfilling
don gregmedlock@patricbrc.org	         0	2017-01-03T19:49:59	folder      	/gregmedlock@patricbrc.org/modelseed/1133568.3/fba
-on gregmedlock@patricbrc.org	    284423	2017-01-03T20:52:02	string      	/gregmedlock@patricbrc.org/modelseed/1133568.3/1133568.3.rxntbl
-on gregmedlock@patricbrc.org	      1145	2017-01-03T20:52:04	job_result  	/gregmedlock@patricbrc.org/modelseed/1133568.3/jobresult
-on gregmedlock@patricbrc.org	   4679910	2017-01-03T19:49:59	genome      	/gregmedlock@patricbrc.org/modelseed/1133568.3/genome
don gregmedlock@patricbrc.org	         0	2017-01-03T20:21:25	folder      	/gregmedlock@patricbrc.org/modelseed/Deino test/gapfilling
-on gregmedlock@patricbrc.org	    346832	2017-01-03T20:23:04	string      	/gregmedlock@patricbrc.org/modelseed/Deino test/Deino test.rxntbl
-on gregmedlock@patricbrc.org	   1446830	2017-01-03T20:23:03	string      	/gregmedlock@patricbrc.org/modelseed/Deino test/Deino test.sbml
-on gregmedlock@patricbrc.org	     75790	2017-01-03T20:23:04	string      	/gregmedlock@patricbrc.org/modelseed/Deino test/Deino test.cpdtbl
don gregmedlock@patricbrc.org	         0	2017-01-03T20:21:25	folder      	/gregmedlock@patricbrc.org/modelseed/Deino test/fba
-on gregmedlock@patricbrc.org	      1983	2017-01-03T20:23:46	job_result  	/gregmedlock@patricbrc.org/modelseed/Deino test/jobresult
-on gregmedlock@patricbrc.org	   5746362	2017-01-03T20:23:04	genome      	/gregmedlock@patricbrc.org/modelseed/Deino test/genome
-on gregmedlock@patricbrc.org	   1636118	2017-01-03T20:23:04	model       	/gregmedlock@patricbrc.org/modelseed/Deino test/model
-on gregmedlock@patricbrc.org	      4460	2017-01-03T20:23:43	string      	/gregmedlock@patricbrc.org/modelseed/Deino test/fba/fba.0.essentials
-on gregmedlock@patricbrc.org	    236147	2017-01-03T20:23:42	string      	/gregmedlock@patricbrc.org/modelseed/Deino test/fba/fba.0.fluxtbl
-on gregmedlock@patricbrc.org	    239435	2017-01-03T20:59:04	string      	/gregmedlock@patricbrc.org/modelseed/Deino test/fba/fba.1.fluxtbl
-on gregmedlock@patricbrc.org	    289552	2017-01-03T20:23:44	fba         	/gregmedlock@patricbrc.org/modelseed/Deino test/fba/fba.0
-on gregmedlock@patricbrc.org	       571	2017-01-03T20:59:05	job_result  	/gregmedlock@patricbrc.org/modelseed/Deino test/fba/fba.1.jobresult
-on gregmedlock@patricbrc.org	    335072	2017-01-03T20:59:04	fba         	/gregmedlock@patricbrc.org/modelseed/Deino test/fba/fba.1
-on gregmedlock@patricbrc.org	      7949	2017-01-03T20:22:48	string      	/gregmedlock@patricbrc.org/modelseed/Deino test/gapfilling/gf.0.gftbl
-on gregmedlock@patricbrc.org	    224070	2017-01-03T20:22:49	string      	/gregmedlock@patricbrc.org/modelseed/Deino test/gapfilling/gf.0.fbatbl
-on gregmedlock@patricbrc.org	   4766816	2017-01-03T20:22:47	fba         	/gregmedlock@patricbrc.org/modelseed/Deino test/gapfilling/gf.0



"Deino test" is my reconstruction from the GUI, so it looks like you're correct. I worked around it by:

1. Creating a new PATRIC account
2. Use the modelseed GUI to build a reconstruction
3. Verified that the reconstruction is in my workspace (interestingly, the reconstruction from the GUI was located in 'folder' rather than modelseed this time)
4. Created a new reconstruction with reconstruct_modelseed_model() and checked the workspace and functions again

Looks like this is working so far, thanks for your help Mike!

**Comment by mmundy42** [comment]
Thanks for reporting the issue. I didn't add back the check for a missing "modelseed" folder when I reorganized the code so I'll get that put back.
